name: Build and Push Podman Image

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Podman
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman
          mkdir -p $HOME/.config/containers
          echo -e "[registries.insecure]\nregistries = [\"ghcr.io\"]" > $HOME/.config/containers/registries.conf

      - name: Build Image
        run: podman build -t ghcr.io/your-username/my-image .

      - name: Push Image
        env:
          REGISTRY_AUTH_FILE: $HOME/.config/containers/auth.json
        run: |
          podman login ghcr.io -u your-username -p ${{ secrets.GHCR_PAT }}
          podman push ghcr.io/your-username/my-image
